### ISSUE TITLE
outdated bundled libxc (4.3.4 vs current 7.0.0) fails to compile with gcc 15.2

### ISSUE THREAD

**Issue by rathann** [merzlab/QUICK#439]
When building AmberTools 25 on Fedora 42, I'm getting the following compilation error:
```
...
[ 46%] Building C object AmberTools/src/quick/src/libxc/CMakeFiles/xc.dir/xc_f.c.o
cd /builddir/build/BUILD/AmberTools-25-build/ambertools25_src/redhat-linux-build/AmberTools/src/quick/src/libxc && /usr/bin/gcc -DCEW -DCEW_USE_DLL -DGNU -DUSE
_CMAKE_MANGLING -I/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/redhat-linux-build/amber-modules/libxc/serial -I/builddir/build/BUILD/AmberTools-2
5-build/ambertools25_src/AmberTools/src/quick/src/libxc/. -I/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/redhat-linux-build/AmberTools/src/quick/
src/libxc -I/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/redhat-linux-build/AmberTools/src/cew/include/cew -std=gnu99 -fPIC -Wno-maybe-uninitiali
zed -O2 -mtune=native -MD -MT AmberTools/src/quick/src/libxc/CMakeFiles/xc.dir/xc_f.c.o -MF CMakeFiles/xc.dir/xc_f.c.o.d -o CMakeFiles/xc.dir/xc_f.c.o -c /buil
ddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c
In file included from /builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:13:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: ‘FortranCInterface_GLOBAL’ declared as function returning a function
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:21:6: note: in expansion of macro ‘FC_FUNC’
   21 | void FC_FUNC(xc_f90_version, XC_F90_VERSION)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c: In function ‘FortranCInterface_GLOBAL’:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: type of ‘xc_f90_version’ defaults to ‘int’ [-Wimplicit-int]
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:21:6: note: in expansion of macro ‘FC_FUNC’
   21 | void FC_FUNC(xc_f90_version, XC_F90_VERSION)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: type of ‘XC_F90_VERSION’ defaults to ‘int’ [-Wimplicit-int]
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:21:6: note: in expansion of macro ‘FC_FUNC’
   21 | void FC_FUNC(xc_f90_version, XC_F90_VERSION)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:24:14: error: ‘major’ undeclared (first use in this function)
   24 |   xc_version(major, minor, micro);
      |              ^~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:24:14: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:24:21: error: ‘minor’ undeclared (first use in this function)
   24 |   xc_version(major, minor, micro);
      |                     ^~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:24:28: error: ‘micro’ undeclared (first use in this function)
   24 |   xc_version(major, minor, micro);
      |                            ^~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c: At top level:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: ‘FortranCInterface_GLOBAL’ declared as function returning a function
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:27:6: note: in expansion of macro ‘FC_FUNC’
   27 | void FC_FUNC(xc_f90_version_string, XC_F90_VERSIN_STRING)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: redefinition of ‘FortranCInterface_GLOBAL’
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:27:6: note: in expansion of macro ‘FC_FUNC’
   27 | void FC_FUNC(xc_f90_version_string, XC_F90_VERSIN_STRING)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: note: previous definition of ‘FortranCInterface_GLOBAL’ with type ‘int()’
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:21:6: note: in expansion of macro ‘FC_FUNC’
   21 | void FC_FUNC(xc_f90_version, XC_F90_VERSION)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c: In function ‘FortranCInterface_GLOBAL’:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: type of ‘xc_f90_version_string’ defaults to ‘int’ [-Wimplicit-int]
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:27:6: note: in expansion of macro ‘FC_FUNC’
   27 | void FC_FUNC(xc_f90_version_string, XC_F90_VERSIN_STRING)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: type of ‘XC_F90_VERSIN_STRING’ defaults to ‘int’ [-Wimplicit-int]
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:27:6: note: in expansion of macro ‘FC_FUNC’
   27 | void FC_FUNC(xc_f90_version_string, XC_F90_VERSIN_STRING)
      |      ^~~~~~~
In file included from /builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:18:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/string_f.h:74:40: error: ‘l1’ undeclared (first use in this function); did you mean ‘ll’?
   74 | #define TO_F_STR1(c, f) to_f_str(c, f, l1)
      |                                        ^~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/string_f.h:62:13: note: in definition of macro ‘to_f_str’
   62 |   ll = (int)l;                             \
      |             ^
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:33:3: note: in expansion of macro ‘TO_F_STR1’
   33 |   TO_F_STR1(version, version_string);
      |   ^~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:33:22: error: ‘version_string’ undeclared (first use in this function); did you mean ‘xc_version_string’?
   33 |   TO_F_STR1(version, version_string);
      |                      ^~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/string_f.h:64:5: note: in definition of macro ‘to_f_str’
   64 |     f[i] = c[i];                           \
      |     ^
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:33:3: note: in expansion of macro ‘TO_F_STR1’
   33 |   TO_F_STR1(version, version_string);
      |   ^~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c: At top level:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: ‘FortranCInterface_GLOBAL’ declared as function returning a function
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:37:16: note: in expansion of macro ‘FC_FUNC’
   37 | CC_FORTRAN_INT FC_FUNC(xc_f90_info_number, XC_F90_INFO_NUMBER)
      |                ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: note: previous definition of ‘FortranCInterface_GLOBAL’ with type ‘int()’
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:21:6: note: in expansion of macro ‘FC_FUNC’
   21 | void FC_FUNC(xc_f90_version, XC_F90_VERSION)
      |      ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c: In function ‘FortranCInterface_GLOBAL’:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: type of ‘xc_f90_info_number’ defaults to ‘int’ [-Wimplicit-int]
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:37:16: note: in expansion of macro ‘FC_FUNC’
   37 | CC_FORTRAN_INT FC_FUNC(xc_f90_info_number, XC_F90_INFO_NUMBER)
      |                ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: type of ‘XC_F90_INFO_NUMBER’ defaults to ‘int’ [-Wimplicit-int]
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:37:16: note: in expansion of macro ‘FC_FUNC’
   37 | CC_FORTRAN_INT FC_FUNC(xc_f90_info_number, XC_F90_INFO_NUMBER)
      |                ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:40:51: error: ‘info’ undeclared (first use in this function)
   40 |   return (CC_FORTRAN_INT) ((xc_func_info_type *)(*info))->number;
      |                                                   ^~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c: At top level:
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: ‘FortranCInterface_GLOBAL’ declared as function returning a function
   27 | #  define FC_FUNC(name, NAME) FortranCInterface_GLOBAL(name, NAME)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/xc_f.c:44:16: note: in expansion of macro ‘FC_FUNC’
   44 | CC_FORTRAN_INT FC_FUNC(xc_f90_info_kind, XC_F90_INFO_KIND)
      |                ^~~~~~~
/builddir/build/BUILD/AmberTools-25-build/ambertools25_src/AmberTools/src/quick/src/libxc/config.h:27:31: error: redefinition of ‘FortranCInterface_GLOBAL’
...
```
... and so on.

It looks like the libxc bundled in src/libxc is a very old version, 4.3.4. Would it be possible to support external libxc instead of bundling an old version?

**Comment by agoetz** [comment]
Thanks for reporting. We have to replicate this. How did you configure AmberTools (cmake command)?

AmberTools25 and QUICK compile and work with gcc 15.2 on macOS. I have older gcc versions on my Linux systems. @ohearnk do you happen to have a dev box with gcc 15.2 to see if you can replicate this error?

Upgrading libcx is low priority. It is considerable work because the interface changed while we ported libxc to GPU and added to QUICK. There have not been relevant additions or bugfixes since 4.3.4. We may look into upgrading after adding improved xc quadrature grids to enable meta-GGA functionals.
